### ISSUE TITLE
Google Places error

### ISSUE THREAD

**Issue by Harryjeffs** [BryanRyczek/GooglePlacesCodable#1]
Upon running the code: I am greeted with this error in the console: "Current Place error: The operation couldn’t be completed. The Places API for iOS is not enabled. See the developer's guide (https://developers.google.com/places/ios-api/start) for how to enable the Google Places API for iOS."

Do you know a fix for this?

**Comment by JDarrenHulipas** [comment]
See this link if is helpful
https://stackoverflow.com/questions/39170293/current-place-error-the-operation-couldn-t-be-completed-google-place-sdk-auto
Sorry for my bad english
